endpoints:
  - name: leantime
    group: core
    url: "http://lks-oss-lb-409784678.us-east-1.elb.amazonaws.com/auth/login"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"

  - name: gatus
    group: core
    url: "http://lks-oss-lb-409784678.us-east-1.elb.amazonaws.com:8080/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"